FROM amazoncorretto:8
WORKDIR /app
COPY . .
# RUN mkdir sources
# RUN find -wholename "./server/src/*.java" > ./sources/source.txt
# RUN mkdir compilation compilation/class
# RUN javac -d ./compilation/class ./sources/@source.txt -classpath /usr/local/share/java/mongodb-driver-sync/bson-4.10.2.jar:/usr/local/share/java/mongodb-driver-sync/bson-record-codec-4.10.2.jar:/usr/local/share/java/mongodb-driver-sync/mongodb-driver-core-4.10.2.jar:/usr/local/share/java/mongodb-driver-sync/mongodb-driver-sync-4.10.2.jar:/home/mbeaudru/.m2/repository/com/github/jkschneider/netty-jssc/0.1.0/netty-jssc-0.1.0.jar:/home/mbeaudru/.m2/repository/io/netty/netty-all/4.0.21.Final/netty-all-4.0.21.Final.jar:/home/mbeaudru/.m2/repository/org/scream3r/jssc/2.8.0/jssc-2.8.0.jar:/home/mbeaudru/.m2/repository/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/home/mbeaudru/.m2/repository/io/github/cdimascio/dotenv-java/3.0.0/dotenv-java-3.0.0.jar:/home/mbeaudru/.m2/repository/at/favre/lib/bcrypt/0.10.2/bcrypt-0.10.2.jar:/home/mbeaudru/.m2/repository/at/favre/lib/bytes/1.5.0/bytes-1.5.0.jar
RUN cd server/src/test/
RUN javac -d ./compliation @source.txt -classpath "../../../../../lib/*"
# (serveur central)
RUN cd ../../.. 
RUN java -classpath "./server/src/test/compliation:../../lib/*" CentralServer 4000

EXPOSE 5000 
# je sais pas si on peut mettre 2 cmd
CMD java -classpath "./server/src/test/compliation:../../lib/*" CentralServer 4000
CMD java -classpath "./server/src/test/compliation:../../lib/*" BaseClient 4000
# CMD java ./compilation/class/CentralServer ./compilation/class/BaseClient